name: cars_encyclopedia_interaction
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  animated_theme_switcher: ^2.0.8
  animations: ^2.0.7
  card_slider: ^1.0.5
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_card_swiper: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon.png"
  fill: false
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/font/
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/font/PlusJakartaSans-Bold.ttf
        - asset: assets/font/PlusJakartaSans-Regular.ttf
        - asset: assets/font/PlusJakartaSans-SemiBold.ttf
        - asset: assets/font/PlusJakartaSans-Medium.ttf
        - asset: assets/font/PlusJakartaSans-Light.ttf
        - asset: assets/font/PlusJakartaSans-ExtraLight.ttf
        